spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        jdbc.batch_size: 15
        order_inserts: true
        order_updates: true
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none

auth:
  jwt:
    access-token-ttl-sec: 86400
    secret-key: ${API_KEY}


logging:
  level:
    spring: debug